# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Alfred.

Build a single-file, windowed .exe:

    pyinstaller build.spec

Output:  dist/Alfred.exe

Tradeoff: ``onefile`` (as opposed to ``onedir``) inflates the
executable to a self-extracting archive that unpacks to a
temp directory at launch -- every cold start pays a few hundred
ms of extraction overhead and the .exe itself is bigger on
disk. The upside is the .exe is a single file the user can
double-click, copy to a USB stick, or pin to the taskbar. For
a personal knowledge-base app launched a handful of times per
day, the simpler distribution story wins.
"""
# PyInstaller exec()s this file with ``Analysis``, ``PYZ`` and
# ``EXE`` already injected into the namespace, so a linter run over
# it will report those names as undefined. That is expected: this is
# a build recipe, not an importable module.

block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    # Bundle the sprite PNGs alongside the executable. They are
    # read-only assets -- the runtime locates them via
    # core.paths.asset_path, which checks sys._MEIPASS first and
    # then falls back to the project tree. The destination
    # directories inside the bundle match the relative paths the
    # helper looks for.
    #
    # The desktop companion plays a multi-state animation whose
    # frames live under ``assets/alfred/frames/{state}/*.png``,
    # with a ``manifest.json`` at the asset root, so we bundle
    # all three state subdirectories AND the manifest. Those
    # frames are also what ``assets/build_icon.py`` crops the app
    # icon from, which keeps the icon and the companion showing
    # the same character.
    #
    # ``icon.ico`` is bundled as data as well as being passed to
    # EXE(icon=...) below. Those are two different jobs: the EXE
    # argument sets the *file* icon Explorer draws, while the
    # bundled copy is what ``ui.app_icon`` loads at runtime for
    # the window, the taskbar button and the tray. Without this
    # line a frozen build found no icon.ico beside itself and
    # silently fell back to the painted placeholder.
    datas=[
        ('assets/alfred/frames/idle/*.png', 'assets/alfred/frames/idle'),
        ('assets/alfred/frames/thinking/*.png', 'assets/alfred/frames/thinking'),
        ('assets/alfred/frames/greeting/*.png', 'assets/alfred/frames/greeting'),
        ('assets/alfred/manifest.json', 'assets/alfred'),
        ('icon.ico', '.'),
    ],
    hiddenimports=[
        # PySide6 plugin modules PyInstaller's static analysis
        # sometimes misses. Listing the common submodules here
        # keeps the build deterministic across PyInstaller
        # versions; the cost of a redundant import is trivial.
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # The ``markdown`` library is pure-Python, ``keyboard`` and
    # ``pynput`` carry native hooks we want included, and
    # ``sqlite3`` is part of the stdlib. None of them need to
    # be excluded.
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# onefile: a single .exe that unpacks at launch. See the
# module-level comment for the tradeoff vs onedir.
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Alfred',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    # windowed: no console window pops up alongside the GUI.
    # Setting this to True would be a major UX bug for a
    # desktop app -- the user just sees a black cmd window.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon.ico is generated by ``assets/build_icon.py``: a
    # gold-rimmed dark plate carrying the mascot, and a gold "A"
    # monogram at 16-32px where a character is all that survives.
    # Windows uses it for the .exe file icon in File Explorer;
    # the runtime icon comes from the bundled copy in ``datas``.
    icon='icon.ico',
)
