"""Tests for the shipped Alfred frame art (``assets/alfred/frames/``).

The sprite engine in :mod:`ui.alfred_pet` is tested elsewhere; this
file tests the *drawings*. The frames are generated by cutting the one
source illustration into head / torso / napkin / legs layers and
transforming each about its own seam, so the failure modes are the ones
a generator produces rather than the ones a hand-illustrator produces:
a pose that came out identical to its neighbour (the animation looks
frozen), a layer that slid far enough to clip the canvas edge, a seam
that opened a translucent pinhole in the middle of the figure, or a
regenerated set that quietly lost a frame.

None of that is visible from the code, and none of it raises -- a
duplicate frame animates perfectly and looks like a bug in the timer.
So the properties are measured off the pixels with Pillow:

* every frame is a 160x160 RGBA PNG matching the manifest
* consecutive frames differ by a real fraction of the figure, so each
  step reads as motion
* the *only* repeated frame is the deliberate hold at the bottom of the
  greeting's bow -- and ``greeting_00`` deliberately re-uses the idle
  rest pose, since a bow starts from standing
* the figure never drifts sideways and never leaves the ground: Alfred
  is a stationary butler, and there are no walking or jumping states
* the thinking pose is distinguishable from idle *above the shoulders*,
  which is where the user actually looks for a "working on it" cue
* no interior pixel is meaningfully translucent, so no layer seam shows
  as a hole against the desktop wallpaper

Thresholds are deliberately loose -- these are "the art is still art"
guards, not a checksum. The tolerances state the measured margin in a
comment so a future regeneration can tell a real regression from a
redraw.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
from PIL import Image

from core.paths import asset_path
from ui.desktop_companion import ASSET_SUBDIR

#: Rows above this are head-and-shoulders. Measured off the idle
#: silhouette, whose figure spans y=15..158 inside the 160px box.
SHOULDER_Y = 60

#: A pixel this opaque is opaque as far as the eye is concerned; the
#: generator's resampling routinely lands a boundary pixel at 249.
OPAQUE = 250

#: An interior pixel below this is a real hole rather than rounding.
#: Measured worst case across all 28 frames: a single pixel at 249.
INTERIOR_MIN_ALPHA = 242

#: The one intentional repeat: the head holds still at the bottom of
#: the bow rather than snapping straight back up.
BOW_HOLD = ("greeting_03.png", "greeting_04.png")


# --- loading ---------------------------------------------------------------


def _frames_dir() -> Path:
    return asset_path(ASSET_SUBDIR) / "frames"


def _manifest() -> dict:
    with (asset_path(ASSET_SUBDIR) / "manifest.json").open(
        "r", encoding="utf-8"
    ) as fh:
        return json.load(fh)


def _paths(state: str) -> list[Path]:
    return sorted((_frames_dir() / state).glob("*.png"), key=lambda p: p.name)


def _load(state: str) -> list[tuple[str, Image.Image]]:
    return [(p.name, Image.open(p).convert("RGBA")) for p in _paths(state)]


STATES = ("idle", "thinking", "greeting")


def _pixels(im: Image.Image):
    """Frame pixels as one 32-bit word each, for fast comparison."""
    return memoryview(im.tobytes()).cast("I")


def _alpha(im: Image.Image) -> bytes:
    return im.getchannel("A").tobytes()


def _footprint(im: Image.Image) -> int:
    """Opaque-enough pixels -- the figure's area on the canvas."""
    return sum(1 for a in _alpha(im) if a > 8)


def _diff_count(a: Image.Image, b: Image.Image) -> int:
    return sum(1 for x, y in zip(_pixels(a), _pixels(b)) if x != y)


def _bbox(im: Image.Image):
    """Bounding box of the visible figure."""
    return im.getchannel("A").point(lambda v: 255 if v > 8 else 0).getbbox()


# --- file layout -----------------------------------------------------------


def test_every_state_has_the_frames_the_manifest_promises():
    """The manifest is the artwork's own record of itself. A regenerated
    set that wrote 6 frames where the manifest says 8 would animate
    happily, just faster and jerkier than designed.
    """
    manifest = _manifest()
    assert set(manifest["states"]) == set(STATES)
    for state in STATES:
        files = _paths(state)
        assert len(files) == manifest["states"][state]["frames"], (
            f"{state}: {len(files)} PNGs but manifest says "
            f"{manifest['states'][state]['frames']}"
        )


def test_frame_filenames_are_a_zero_padded_sequence_from_zero():
    """Sorting is lexicographic, so the numbering is what fixes frame
    order. ``idle_8.png`` would sort before ``idle_10.png`` and play the
    animation out of sequence with no error anywhere.
    """
    for state in STATES:
        names = [p.name for p in _paths(state)]
        expected = [f"{state}_{i:02d}.png" for i in range(len(names))]
        assert names == expected, f"{state} frames are not a 00..NN sequence"
        for name in names:
            assert re.fullmatch(rf"{state}_\d\d\.png", name)


def test_frames_are_rgba_at_the_manifest_size():
    """RGBA is not decoration: the companion is a translucent window, so
    a frame saved without an alpha channel would paint a solid
    rectangle over the wallpaper."""
    width, height = _manifest()["size"]
    assert (width, height) == (160, 160)
    for state in STATES:
        for name, im in _load(state):
            assert im.size == (width, height), f"{name} is {im.size}"
            assert im.mode == "RGBA", f"{name} is mode {im.mode}"


def test_no_frame_is_blank_or_nearly_blank():
    """A layer transform that pushed everything off-canvas produces a
    valid PNG of nothing, which reads as the sprite flickering out."""
    for state in STATES:
        for name, im in _load(state):
            footprint = _footprint(im)
            # Measured range across the set: 4962..6196 px.
            assert footprint > 3000, f"{name} draws only {footprint} px"


# --- placement on the canvas ----------------------------------------------


def test_no_frame_is_clipped_by_the_canvas():
    """Every pose has to fit the 160x160 box the widget is fixed at.

    A figure touching an edge means the pose was cropped; there is no
    scaling in the display path (``setScaledContents(False)``), so what
    is cut here is cut on screen.
    """
    for state in STATES:
        for name, im in _load(state):
            left, top, right, bottom = _bbox(im)
            assert left > 0, f"{name} touches the left edge"
            assert top > 0, f"{name} touches the top edge"
            assert right < im.width, f"{name} touches the right edge"
            assert bottom < im.height, f"{name} touches the bottom edge"


def test_the_figure_never_drifts_sideways_or_leaves_the_ground():
    """Alfred is a stationary desktop butler.

    Every frame of every state shares one left edge and one bottom edge:
    the body is anchored and the feet are planted, and the animation
    happens above them. This is the pixel-level counterpart of the
    engine having no walking, running, jumping or falling states -- a
    pose that shifted the whole figure would read as a step.
    """
    lefts, bottoms = set(), set()
    for state in STATES:
        for _name, im in _load(state):
            left, _top, _right, bottom = _bbox(im)
            lefts.add(left)
            bottoms.add(bottom)
    assert len(lefts) == 1, f"the figure drifts horizontally: {sorted(lefts)}"
    assert len(bottoms) == 1, f"the feet leave the ground: {sorted(bottoms)}"


# --- motion between frames ------------------------------------------------


def test_consecutive_frames_differ_by_a_real_share_of_the_figure():
    """Each step has to move enough of the figure to be seen.

    The comparison is against the figure's own area rather than the
    canvas, because a change of 300 pixels is a twitch on a 5,000-pixel
    butler and a redraw on a 500-pixel one. The wrap from the last frame
    back to the first is included -- these are loops, and a seam there
    shows as a stutter once per cycle.

    Measured: 62%-82% of the footprint per step. The one exception is
    the deliberate hold at the bottom of the greeting's bow.
    """
    for state in STATES:
        frames = _load(state)
        mean_footprint = sum(_footprint(im) for _, im in frames) / len(frames)
        for i, (name, im) in enumerate(frames):
            nxt_name, nxt = frames[(i + 1) % len(frames)]
            if (name, nxt_name) == BOW_HOLD:
                continue
            share = _diff_count(im, nxt) / mean_footprint
            assert share >= 0.15, (
                f"{name} -> {nxt_name} moves only {share:.1%} of the figure"
            )
            assert share <= 2.0, (
                f"{name} -> {nxt_name} changes {share:.1%} of the figure -- "
                "that is a different drawing, not a step of one animation"
            )


def test_the_only_repeated_frame_is_the_hold_at_the_bottom_of_the_bow():
    """One pair of identical frames is intended; a second pair is a
    generator that emitted the same transform twice.

    The hold is what makes the bow read as a bow rather than a bounce:
    the head reaches its lowest point and stays there for one frame
    before coming back up.
    """
    repeats: list[tuple[str, str]] = []
    for state in STATES:
        frames = _load(state)
        for i in range(len(frames)):
            for j in range(i + 1, len(frames)):
                if frames[i][1].tobytes() == frames[j][1].tobytes():
                    repeats.append((frames[i][0], frames[j][0]))
    assert repeats == [BOW_HOLD], f"unexpected duplicate frames: {repeats}"


def test_the_greeting_starts_from_the_idle_rest_pose():
    """``greeting_00`` is the idle rest frame, and that is deliberate: a
    bow begins from standing, so the one-shot can start without a jump
    from whatever frame idle happened to be on.

    It is also the only frame shared between two states -- anything else
    matching across states would mean a pose was copied rather than
    drawn.
    """
    by_name: dict[tuple[str, str], bytes] = {}
    for state in STATES:
        for name, im in _load(state):
            by_name[(state, name)] = im.tobytes()

    keys = list(by_name)
    cross = [
        (a, b)
        for i, a in enumerate(keys)
        for b in keys[i + 1:]
        if a[0] != b[0] and by_name[a] == by_name[b]
    ]
    assert cross == [(("idle", "idle_00.png"), ("greeting", "greeting_00.png"))], (
        f"unexpected frames shared between states: {cross}"
    )


def test_the_greeting_is_a_bow_that_goes_down_holds_and_comes_back():
    """The shape of the one-shot, read off the top of the figure.

    The head descends for the first half, holds for one frame at the
    bottom, then rises back to near its starting height. Getting this
    backwards (or flat) is the kind of frame-order mistake that plays
    smoothly and still looks wrong.
    """
    tops = [_bbox(im)[1] for _name, im in _load("greeting")]
    lowest = max(tops)  # a larger y is a lower head
    bottom_at = tops.index(lowest)

    assert tops[0] < lowest, "the greeting does not start standing"
    assert tops[:bottom_at + 1] == sorted(tops[:bottom_at + 1]), (
        f"the head does not descend monotonically: {tops}"
    )
    assert tops[bottom_at + 1] == lowest, "no hold at the bottom of the bow"
    rise = tops[bottom_at + 1:]
    assert rise == sorted(rise, reverse=True), (
        f"the head does not come back up cleanly: {tops}"
    )
    assert tops[-1] <= tops[0], "the bow ends lower than it started"


def test_thinking_is_distinguishable_from_idle_above_the_shoulders():
    """The thinking cue has to be legible where the user looks.

    Idle and thinking are both gentle loops of the same figure, so it is
    entirely possible to generate a thinking set that differs only in
    how the legs are shaded -- perfectly measurable, completely
    invisible. Comparing only the head-and-shoulders band forces the
    difference to be somewhere it will be noticed.

    Compared index-for-index over idle's 8 frames, which is the worst
    case: at any given moment the two loops are at frames that ought to
    look different.
    """
    idle = _load("idle")
    thinking = _load("thinking")
    for i, (idle_name, idle_im) in enumerate(idle):
        think_name, think_im = thinking[i]
        band = (0, 0, idle_im.width, SHOULDER_Y)
        differing = _diff_count(idle_im.crop(band), think_im.crop(band))
        # Measured minimum across the 8 pairs: 778 px.
        assert differing > 200, (
            f"{think_name} is nearly identical to {idle_name} above "
            f"y={SHOULDER_Y} ({differing} px differ)"
        )


def test_thinking_reaches_outside_the_resting_silhouette():
    """Thinking lifts something clear of the body -- it is taller and
    wider than the resting pose in every frame.

    This is also why the bubble's anchor offsets in
    :mod:`ui.capture_popup` are measured off the resting body box rather
    than off the widest pose: anchoring to the thinking silhouette would
    push the tail away from the mouth.
    """
    idle_boxes = [_bbox(im) for _name, im in _load("idle")]
    idle_right = max(box[2] for box in idle_boxes)
    idle_top = min(box[1] for box in idle_boxes)

    for name, im in _load("thinking"):
        left, top, right, bottom = _bbox(im)
        assert right > idle_right, (
            f"{name} is no wider than the resting pose "
            f"(right={right}, idle right={idle_right})"
        )
        assert top < idle_top, (
            f"{name} is no taller than the resting pose "
            f"(top={top}, idle top={idle_top})"
        )


# --- seam integrity --------------------------------------------------------


def test_no_interior_pixel_is_translucent():
    """A hole in the middle of the figure shows the wallpaper through it.

    The frames are composited from separately-transformed layers, so a
    seam that opens by a pixel leaves a visible pinhole -- and against a
    translucent, always-on-top window it is the desktop that shows
    through, not a background colour, which makes it obvious on screen
    and invisible in code.

    "Interior" means every one of the eight neighbours is opaque,
    diagonals included, so an antialiased outline never qualifies.
    Measured worst case across all 28 frames: one pixel at alpha 249.
    """
    for state in STATES:
        for name, im in _load(state):
            alpha = _alpha(im)
            width, height = im.size
            for y in range(1, height - 1):
                row = y * width
                for x in range(1, width - 1):
                    value = alpha[row + x]
                    if value >= INTERIOR_MIN_ALPHA:
                        continue
                    neighbours = (
                        alpha[row + x - 1], alpha[row + x + 1],
                        alpha[row - width + x], alpha[row + width + x],
                        alpha[row - width + x - 1], alpha[row - width + x + 1],
                        alpha[row + width + x - 1], alpha[row + width + x + 1],
                    )
                    assert min(neighbours) < OPAQUE, (
                        f"{name}: pinhole at ({x}, {y}) -- alpha {value} "
                        "surrounded by opaque pixels"
                    )


def test_the_source_drawing_and_generator_named_by_the_manifest_exist():
    """The frames are derived art. If the source drawing or the
    generator goes missing, the set can never be regenerated -- and the
    manifest is the only record of where they were.
    """
    base = asset_path(ASSET_SUBDIR)
    source = base / _manifest()["source"]
    assert source.is_file(), f"missing source drawing: {source}"
    assert Image.open(source).size == tuple(_manifest()["size"])

    generator = Path(_manifest()["generator"])
    candidates = [generator, asset_path(str(generator))]
    assert any(p.is_file() for p in candidates), (
        f"missing frame generator: tried {[str(p) for p in candidates]}"
    )


def test_the_manifest_records_which_states_loop():
    """``loop`` is documentation of the engine's own behaviour: idle and
    thinking wrap, greeting is the one-shot that hands back to idle."""
    states = _manifest()["states"]
    assert states["idle"]["loop"] is True
    assert states["thinking"]["loop"] is True
    assert states["greeting"]["loop"] is False


@pytest.mark.parametrize("absent", ["walking", "running", "sleeping", "jumping"])
def test_no_art_exists_for_the_states_alfred_deliberately_lacks(absent):
    """The character is a stationary butler. Art appearing for one of
    these would mean someone started adding a state the engine has no
    timing, no transition, and no design for.
    """
    assert not (_frames_dir() / absent).exists()
    assert absent not in _manifest()["states"]
